version: '2.1'

services:
    plex:
        extends:
            file: ../base.yaml
            service: app
        container_name: plex
        image: plexinc/pms-docker:plexpass
        volumes:
            - ${base_folder}/vault:/data
            - ${data_folder}/plex/config:/config
            - /tmp/transcode/plex:/transcode
        cap_add:
            - SYS_ADMIN
        privileged: true
        restart: always
        ports:
            - 32400:32400/tcp
            - 3005:3005/tcp
            - 8324:8324/tcp
            - 32469:32469/tcp
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
            - 33400:33400/tcp
            - 33443:33443/tcp
