version: '2.1'

services:
    nginx:
        extends:
            file: ../base.yml
            service: app
        container_name: nginx
        image: nginx:mainline-alpine
        volumes:
            - ${data_folder}/nginx/www:/usr/share/nginx/html
        restart: always
        ports:
            - 8000:80
